---
  name: Continuous Integration

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  env:
    DOTNET_VERSION: 8.0.x
    DOTNET_CONFIGURATION: Release

  jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
        issues: read
        checks: write
        pull-requests: write

      steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - name: Restore dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore --configuration $DOTNET_CONFIGURATION
        - name: Test
          run: dotnet test --no-build --configuration $DOTNET_CONFIGURATION --logger trx --verbosity normal
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always()
          with:
            files: |
              **/*.trx
        - name: Push package to GitHub packages
          if: github.ref == 'refs/heads/main'
          run: dotnet nuget push ./**/*.nupkg --source "https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
